CLASS PIERWSZY
{
	PUBLIC STATIC VOID MAIN(sTRING [] ARGS)
	{
		sYSTEM.OUT.PRINTLN("HELLO WORLD");
		INT I;
		FOR (I=0; I<ARGS.LENGTH; I++) //WYPISUJE CO SIE PODALO W CMD PO JAVA PIERWSZY XX
		sYSTEM.OUT.PRINTLN(ARGS[I]);
	}
}
